# Generated by Django 6.0.5 on 2026-05-14 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=100)),
                ('warna', models.CharField(blank=True, max_length=100, null=True)),
                ('merek', models.CharField(blank=True, max_length=100, null=True)),
                ('deskripsi', models.TextField()),
                ('ciri_khas', models.TextField(blank=True, null=True)),
                ('foto_barang', models.ImageField(upload_to='barang/')),
                ('status', models.CharField(choices=[('hilang', 'Kehilangan'), ('temuan', 'Temuan'), ('selesai', 'Selesai')], max_length=20)),
                ('lokasi', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('tanggal_kejadian', models.DateField()),
                ('status_verifikasi', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
