# Generated by Django 6.0.5 on 2026-05-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_shift', models.CharField(choices=[('pagi', 'Pagi'), ('sore', 'Sore'), ('malam', 'Malam')], max_length=20)),
                ('nomor_whatsapp', models.CharField(max_length=20)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
    ]
