# Generated by Django 6.0.5 on 2026-05-14 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_securityshift_created_at_securityshift_nama_security'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ciri_khas',
        ),
        migrations.AddField(
            model_name='securityshift',
            name='tanggal_jaga',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='kategori',
            field=models.CharField(choices=[('Elektronik', 'Elektronik'), ('Fashion', 'Fashion'), ('Dokumen', 'Dokumen'), ('Aksesoris', 'Aksesoris'), ('Tas', 'Tas'), ('Dompet', 'Dompet'), ('Kunci', 'Kunci'), ('Kendaraan', 'Kendaraan'), ('Helm', 'Helm'), ('Botol Minum', 'Botol Minum'), ('Laptop', 'Laptop'), ('Handphone', 'Handphone'), ('Jam Tangan', 'Jam Tangan'), ('Perhiasan', 'Perhiasan'), ('Lainnya', 'Lainnya')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
