# Generated by Django 6.0.5 on 2026-05-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_ciri_khas_securityshift_tanggal_jaga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='catatan_penyerahan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='dokumentasi_penyerahan',
            field=models.ImageField(blank=True, null=True, upload_to='serah_terima/'),
        ),
        migrations.AddField(
            model_name='report',
            name='ktm_penemu',
            field=models.ImageField(blank=True, null=True, upload_to='serah_terima/'),
        ),
        migrations.AddField(
            model_name='report',
            name='ktm_penerima',
            field=models.ImageField(blank=True, null=True, upload_to='serah_terima/'),
        ),
        migrations.AddField(
            model_name='report',
            name='lokasi_penyerahan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='nama_penemu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='nama_penerima',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='petugas_penyerahan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='securityshift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='foto_barang',
            field=models.ImageField(blank=True, null=True, upload_to='barang/'),
        ),
    ]
