# Generated by Django 6.0.5 on 2026-06-09 07:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_catatan_penyerahan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityshift',
            name='group_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
    ]
