# Generated by Django 6.0.5 on 2026-06-10 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_securityshift_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='petugas_serah_terima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.securityshift'),
        ),
        migrations.AddField(
            model_name='report',
            name='tanggal_serah_terima',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
